# The URL the site will be built for
base_url = "https://hackers267.github.io/nginx-note"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme="blow"
default_language="zh"
title = "Nginx"
taxonomies = [
  { name = "tags", rss = true, feed = true },
  { name = "categories", rss = true, feed = true },
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
enable_sidebar = false
enable_multilingue = false
enable_search = false

[extra.navbar]
title = "Nginx"
items = [
  { lang = "zh", links = [{ url = "/", name = "主页" }, { url = "/post", name = "文章" }, { url = "/tags", name = "标签" }, { url = "/categories", name = "分类" }] },
]

[extra.index]
title = "Nginx"
image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM-zyAiCFPeOX9-wj_u-iPxXvvy3IxXcGr-YRY4na7X96ahZS4ms-cZhmXlf-FSVJBPwU&usqp=CAU"
image_alt = "Nginx"

[extra.social]
gitlab = false
github = "https://github.com/hackers267"
twitter = false
linkedin = false
stackoverflow = false
telegram = false
email = "silence_zhpf@aliyun.com"

[extra.default_author]
name = "silence_zhpf"
avatar = "https://avatars.githubusercontent.com/u/22020318?v=4"
avatar_alt = "silence_zhpf"
